services:
      
  grpc-service-1-envoy:
    image: envoyproxy/envoy:v1.30.1
    volumes:
      - ./grpc-service-1-envoy.yaml:/envoy.yaml
    command:
      -c /envoy.yaml
    ports:
      - 10001:8000
      
  grpc-service-2-envoy:
    image: envoyproxy/envoy:v1.30.1
    volumes:
      - ./grpc-service-2-envoy.yaml:/envoy.yaml
    command:
      -c /envoy.yaml
    ports:
      - 10002:8000
      
  grpc-service-3-envoy:
    image: envoyproxy/envoy:v1.30.1
    volumes:
      - ./grpc-service-3-envoy.yaml:/envoy.yaml
    command:
      -c /envoy.yaml
    ports:
      - 10003:8000
