# services listen on localhost only, port 20000
# envoy sidecar accesses them via localhost:20000
# and envoy runs on 8000 port externally

services:
  grpc-service-1-envoy:
    build: .
    volumes:
      - ./grpc-sidecar-envoy.yaml:/envoy.yaml
    environment:
      SERVICE_NAME: Test1

  grpc-service-2-envoy:
    build: .
    volumes:
      - ./grpc-sidecar-envoy.yaml:/envoy.yaml
    environment:
      SERVICE_NAME: Test2

  grpc-service-3-envoy:
    build: .
    volumes:
      - ./grpc-sidecar-envoy.yaml:/envoy.yaml
    environment:
      SERVICE_NAME: Test3
