{
 "title": "HTTP proxy",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Total bytes sent",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "envoy_http_downstream_cx_tx_bytes_total{envoy_http_conn_manager_prefix=\"ingress_http\", instance=\"http-proxy:9000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total bytes received",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "envoy_http_downstream_cx_rx_bytes_total{instance=\"http-proxy:9000\", envoy_http_conn_manager_prefix=\"ingress_http\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Total requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "envoy_http_downstream_rq_total{envoy_http_conn_manager_prefix=\"ingress_http\", instance=\"http-proxy:9000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "envoy_http_downstream_cx_total{instance=\"http-proxy:9000\", envoy_http_conn_manager_prefix=\"ingress_http\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total active connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "envoy_http_downstream_cx_active{envoy_http_conn_manager_prefix=\"ingress_http\", instance=\"http-proxy:9000\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}