services:
  
  http-proxy:
    image: envoyproxy/envoy:v1.30.1
    volumes:
      - ./http-proxy-envoy.yaml:/envoy.yaml
    command:
      -c /envoy.yaml
    ports:
      - 8000:8000 # http proxy
      - 9000:9000 # admin interface
