# services listen on localhost only, port 20000
# envoy sidecar accesses them via localhost:20000
# and envoy runs on 8000 port externally

services:
  http-service-1-envoy:
    build: .
    volumes:
      - ./http-sidecar-envoy.yaml:/envoy.yaml
    environment:
      SERVICE_NAME: service-1
    depends_on:
      postgres-service:
        condition: service_healthy

  http-service-2-envoy:
    build: .
    volumes:
      - ./http-sidecar-envoy.yaml:/envoy.yaml
    environment:
      SERVICE_NAME: service-2
    depends_on:
      postgres-service:
        condition: service_healthy

  http-service-3-envoy:
    build: .
    volumes:
      - ./http-sidecar-envoy.yaml:/envoy.yaml
    environment:
      SERVICE_NAME: service-3
    depends_on:
      postgres-service:
        condition: service_healthy
