services:

  grpc-proxy:
    image: envoyproxy/envoy:v1.30.1
    volumes:
      - ./grpc-proxy-envoy.yaml:/envoy.yaml
    command:
      -c /envoy.yaml
    ports:
      - 10000:8000 # grpc
      - 11000:9000 # admin
